[package]
name = "bullet-bored"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
miniquad = "0.3.14"
native-dialog = "0.6.3"
rhai = "1.12.0"
